var keywords, adCont, debug = false;

function addAffiliateLinks() {

	try {

		/*if (location.host.indexOf('www.amazon.') != 0) {
			
			var tag = 'hovzoo',
				suffixes = {'com': '-20', 'fr': '-21', 'es': '05f-21', 'it': '01-21', 'de': '0f-21', 'ca': '05-20', 'co.uk': '08-21'};
			
			function appendTag(eventObject) {
				var href = this.href,
					tld = href.split('/')[2].replace('www.amazon.',''),
					suffix = suffixes[tld];
				if (suffix && href.match(/\/(dg|gp|dp)\//) && !href.match(/[\&\?]tag\=/)) {
					if (href.indexOf('?') == -1) {
						href += "?";
					} else {
						href += "&"
					}
					href += "tag=" + tag + suffix;
					this.href = href;
				}
			}

			$('body').delegate('a[href*="www.amazon."]', 'hover', appendTag);
		}*/

		if (!debug && Math.random() > 0.3) { return; }

		if (location.host == 'www.facebook.com') {
			adCont = document.getElementById('pagelet_ego_pane_w');
			if (!adCont) { return; }
			
			keywords = getKeywords();
			if (debug) { console.log(keywords); }
			//keywords = 'kid cudi';
			if (!keywords) { return; }
			
			/*var storedItem = localStorage['hzAdCache ' + keywords];		
			if (storedItem) {
				storedItem = JSON.parse(storedItem);
				
				// Invalid search terms are re-tested after 10 days
				if (storedItem.asin == '0' && Date.now() - storedItem.timestamp < 3600000 * 24 * 10) {
					//console.log('invalid keywords: ' + keywords);
					return; 
				
				// Valid search terms are cached for a day
				} else if (storedItem.asin != '0' && Date.now() - storedItem.timestamp < 3600000 * 24) {
					//console.log('ad from cache: ' + keywords);
					createAffiliatelinks(storedItem);
					return;
					
				} else {
					localStorage.removeItem('hzAdCache ' + keywords);
				}
			}*/
			
			searchItems(keywords);
		} 
	}
	catch(e) { if (debug) { console.error(e); } }
}

function getKeywords() {
	var i, elem, elems;
	elems = document.querySelectorAll('a[data-hovercard*="hovercard/page"], #pagelet_ego_pane_w .actorName a');
	//console.log(elems);
	if (elems.length > 0)
		return elems[Math.floor(Math.random()*elems.length)].textContent;
	else
		return null;
}

function searchItems(keywords) {
	var searchURL,
		xhr = new XMLHttpRequest();
	if (location.protocol == 'https:') {
		searchURL = 'https://ssl14.ovh.net/~hoverzoo';
	} else {
		searchURL = 'http://hoverzoom.net';
	}
	searchURL += '/api/amazon/getlinks/?cv=4.7&kw=' + encodeURIComponent(keywords);
	xhr.onreadystatechange = function() { 
		if(xhr.readyState == 4) {
			if (xhr.status == 200) {
				try {
					var data = JSON.parse(xhr.responseText);
	if (debug) { console.log(data) };
					if (data && data.items) {
						createAffiliatelinks(data); 
					}
				}
				catch(e) { if (debug) { console.error(e); } }
			}
		}
	};
	xhr.open('GET', searchURL, true);                  
	xhr.send(null);
	//if (debug) {console.log(searchURL);}
}

function createAffiliatelinks(data) {

	try {

		var item = data.items[0],
			text = item.title + '<br>',
			tld = item.url.split('/')[2].replace('www.amazon.', '');
		
		
		/*if (suffixes[navigator.language]) {
			AssociateTag += suffixes[navigator.language];
		} else {
			AssociateTag += '-20';
		}*/
			
		/*if (item.bestPrice && item.listPrice)
			text += '<br>Best price <b>' + item.bestPrice + '</b><br>or Buy New <b>' + item.listPrice + '</b>';
		else if (item.listPrice || item.bestPrice)
			text += '<br>Buy for <b>' + item.listPrice || item.bestPrice + '</b>';*/
		text += '<br><b>' + item.listPrice || item.bestPrice + '</b>';

		var html = '<div id="hoverZoomAd" class="ego_column" style="padding-top: 8px;border-top: 1px solid #E9E9E9;"><div class="ego_section"><div class="ego_unit_container"><div class="fbEmuEgoUnit ego_unit"><div class="fbAdUnit"><div class="fbEmu fbEmuEgo">';
		html += '<div class="uiSelector inlineBlock emu_x emuEventfad_hide  fbEmuLink uiSelectorRight"><div class="wrap"><a id="hzCloseAd" style="visibility: hidden" href="#" onclick="alert(\'This ad was generated by Hover Zoom.\\nVisit Hover Zoom’s options page to learn more or opt out of personalized ads.\');return false;"><img src="' + chrome.extension.getURL('images/fb-close.png') + '"></a></div></div>';
		html += '<div class="title" style="color: #3B5998; font-weight: bold"><a class="forceLTR" href="' + item.url + '" target="_blank">' + keywords + '</a></div>';
		
		/*var host = item.url.split('/')[2];
		if (host)
			html += '<div class="adInfo"><a class="identity emuEvent1 fbEmuLink" href="' + item.url + '" target="_blank">' + host.replace('www.', '') + '</a></div>';*/
		
		html += '<div class="clearfix uiImageBlock image_body_block"><a class="emuEvent1  fbEmuLink image fbEmuImage uiImageBlockImage uiImageBlockMediumImage lfloat" style="width: 80px" href="' + item.url + '" target="_blank" style="margin-right: 5px">';
		html += '<img src="http://ws.assoc-amazon.' + tld + '/widgets/q?_encoding=UTF8&Format=_SL80_&ASIN=' + item.asin + '&ID=AsinImage&WS=1&ServiceVersion=20070822"></a><div>';
		html += '<div class="uiImageBlockContent "><div class="body"><a class="forceLTR emuEvent1  fbEmuLink" style="color: #333" href="' + item.url + '" target="_blank">' + text + '</a></div></div>';
		html += '</div></div></div></div></div></div>';
		window.removeEventListener('DOMNodeInserted', windowOnDOMNodeInserted);
		adCont.innerHTML += html;
		window.addEventListener('DOMNodeInserted', windowOnDOMNodeInserted);
		$('#hoverZoomAd').mouseenter(function() {
			$('#hzCloseAd').css('visibility', 'visible');
		});
		$('#hoverZoomAd').mouseleave(function() {
			$('#hzCloseAd').css('visibility', 'hidden');
		});
		chrome.extension.sendRequest({action: 'trackEvent', event: {category: 'Ads', action: 'FacebookAdDisplayed', label: keywords.replace(/['"]/g, ' ')}});
		$('#hoverZoomAd').click(function() {
			chrome.extension.sendRequest({action: 'trackEvent', event: {category: 'Ads', action: 'FacebookAdClicked', label: keywords.replace(/['"]/g, ' ')}});
		});
	
	} 
	catch(e) { if (debug) { console.error(e); } }
	//console.log('FacebookAdDisplayed: ' + keywords);
}

function windowOnDOMNodeInserted(event) {
	/*if (event.target && event.target.id)
		console.log(event.target.id);*/
	if (event.target && event.target.id == 'egoRefreshAds' && !document.getElementById('hoverZoomAd')) {
		addAffiliateLinks();
		//if (debug) { console.log('Ad refresh'); }
	}
}

chrome.extension.sendRequest({action : 'getOptions'}, function (options) {
	if (options.enableAds < 2) {
		addAffiliateLinks();
		if (location.host == 'www.facebook.com') {
			window.addEventListener('DOMNodeInserted', windowOnDOMNodeInserted);
		}
	}
});